### ISSUE TITLE
async logging

### ISSUE THREAD

**Issue by MajidDehnamaki** [CurtisInstruments/NLog.Targets.Sentry#2]
I have 2 question
1-can I use async logging?
2-how set tags or extra data in` nlog.config `?show me example please

**Comment by willson556** [comment]
1. I haven't tried it, but I can't see why using NLog's [AsyncWrapper target](https://github.com/nlog/NLog/wiki/AsyncWrapper-target) would cause any problems. If it doesn't work for you, feel free to reply with the issue(s) you encounter.

2. There's currently only one option available for configuring tags & extras and that's the `SendLogEventInfoPropertiesAsTags` property. If set to true, it will take any properties from a log event and send them as tags. Normally, these are stored as [extras](https://docs.sentry.io/learn/context/#extra-context). Taking advantage of [structured logging in NLog](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging) would be one way of taking advantage of the existing functionality. If you have other functionality in mind, feel free to file new issues with specific requests or to submit a pull request.
