### ISSUE TITLE
Convert DSN to use Layouts

### ISSUE THREAD

**Issue by Thaureon** [CurtisInstruments/NLog.Targets.Sentry#4]
With the move to .NET Core we can pull variables from the appsettings.json file with the configSetting layout as described [here](https://github.com/NLog/NLog/wiki/ConfigSetting-Layout-Renderer), but this requires the NLog target to handle layouts.

Can we move DSN to use type Layout instead of type string in the Sentry Target?

**Comment by willson556** [comment]
Will this break compatibility with existing config files? If not, please feel free to submit a pull request!

**Comment by devigo** [comment]
It will be fixed when this pull request is merged. #5

**Comment by willson556** [comment]
Resolved by #5.
